import '@styles/globals.css';

import { Inter } from 'next/font/google'
import Nav from '@components/Nav';
import Provider from "@components/Provider";


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {



    return (
        <html lang="en">
            <head><link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" /></head>
            <body className={inter.className + " bg-[#e4e6f0]"}>
                <Provider>
                    <Nav />
                    {children}

                </Provider>

            </body>
        </html>
    )
}
